image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/docker:20.10.15
services:
  - docker:dind

stages:
  - build
  - scenarios

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

midas-mosaik-baseimage-build:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # build midas-mosaik baseimage
    #- apk add --no-cache python3 py3-pip
    - cd gitlab_ci
    - ash build_midas_baseimage.sh
  artifacts:
    paths:
      - gitlab_ci/midas_version.txt
    expire_in: 1 hour

docker-build:
  stage: build
  needs: [midas-mosaik-baseimage-build]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    # create docker image specifically for this branch/tag
    - docker build --build-arg MIDAS_MOSAIK_VERSION=$(cat gitlab_ci/midas_version.txt) -t $IMAGE_NAME . -f gitlab_ci/Dockerfile.smasher
    - docker push $IMAGE_NAME

powergrid_scenario:
  image: $IMAGE_NAME
  stage: scenarios
  script:
    - python3 src/smasher/scripts/powergrid_attack.py